/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

import {
  AppHome as AppHome
} from './components/app-home/app-home';

declare global {
  interface HTMLAppHomeElement extends AppHome, HTMLElement {
  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-home": JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppProfile as AppProfile
} from './components/app-profile/app-profile';

declare global {
  interface HTMLAppProfileElement extends AppProfile, HTMLElement {
  }
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-profile": JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AboutComponent as AboutWebshop
} from './containers/about/about';

declare global {
  interface HTMLAboutWebshopElement extends AboutWebshop, HTMLElement {
  }
  var HTMLAboutWebshopElement: {
    prototype: HTMLAboutWebshopElement;
    new (): HTMLAboutWebshopElement;
  };
  interface HTMLElementTagNameMap {
    "about-webshop": HTMLAboutWebshopElement;
  }
  interface ElementTagNameMap {
    "about-webshop": HTMLAboutWebshopElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "about-webshop": JSXElements.AboutWebshopAttributes;
    }
  }
  namespace JSXElements {
    export interface AboutWebshopAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  ShoppingListOverview as ShoppingListOverview
} from './containers/shopping-list-overview/shopping-list-overview';

declare global {
  interface HTMLShoppingListOverviewElement extends ShoppingListOverview, HTMLElement {
  }
  var HTMLShoppingListOverviewElement: {
    prototype: HTMLShoppingListOverviewElement;
    new (): HTMLShoppingListOverviewElement;
  };
  interface HTMLElementTagNameMap {
    "shopping-list-overview": HTMLShoppingListOverviewElement;
  }
  interface ElementTagNameMap {
    "shopping-list-overview": HTMLShoppingListOverviewElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "shopping-list-overview": JSXElements.ShoppingListOverviewAttributes;
    }
  }
  namespace JSXElements {
    export interface ShoppingListOverviewAttributes extends HTMLAttributes {
      
    }
  }
}

